#!/usr/bin/env python3
"""Render the ascender.ansible.com CRDs from the awx.ansible.com ones.

The two groups describe the same four resources, and a CRD belongs to exactly
one group, so there is no way to serve both from one file. Keeping two copies by
hand is the arrangement that drifts: three thousand lines of schema, edited on
one side, silently different on the other, and the symptom is a field that
validates under one kind and not the other.

So one side is generated. `make crds` writes the ascender files from the awx
ones and CI fails if the result differs from what is committed, which is the
same shape as the generated API types check.

The transform is two string replacements, and the reason that is safe is worth
stating: the CRDs contain no schema property whose name mentions AWX, and the
CSV describes no spec path that does. Every occurrence is the group, a kind, a
plural, a singular, or prose. Adding a property called `awx_something`, or one
called `something_awx`, would break that, so the checks below parse the YAML and
refuse rather than renaming a field out from under a user.

The CSV owned entries are generated too. Every CRD in the bundle has to be
declared there or OLM does not treat it as owned, and the AWX entry alone
carries over a hundred spec descriptors, which is not a thing to copy by hand.
"""

import pathlib
import re
import sys

import yaml

CONFIG = pathlib.Path(__file__).resolve().parent.parent / 'config'
BASES = CONFIG / 'crd' / 'bases'
SAMPLES = CONFIG / 'samples'
CSV = CONFIG / 'manifests' / 'bases' / 'awx-operator.clusterserviceversion.yaml'
SOURCE_GROUP = 'awx.ansible.com'
TARGET_GROUP = 'ascender.ansible.com'

OWNED_KEY = '    owned:'
BEGIN = '    # BEGIN generated by hack/render-ascender-crds.py, do not edit by hand'
END = '    # END generated'


def render(source: str) -> str:
    return source.replace('AWX', 'Ascender').replace('awx', 'ascender')


def mapping_keys(node):
    """Every mapping key in a parsed document, at any depth."""
    if isinstance(node, dict):
        for key, value in node.items():
            yield key
            yield from mapping_keys(value)
    elif isinstance(node, list):
        for value in node:
            yield from mapping_keys(value)


def offending_key(text: str):
    """A mapping key mentioning awx anywhere, which render() would rewrite."""
    for key in mapping_keys(yaml.safe_load(text)):
        if 'awx' in str(key).lower():
            return str(key)
    return None


def render_files(sources, targets_dir, expected):
    for source in sources:
        text = source.read_text()
        offender = offending_key(text)
        if offender is not None:
            print(f'{source.name} has a key named {offender}, which this cannot rename', file=sys.stderr)
            return 1
        target = targets_dir / render(source.name)
        target.write_text(render(text))
        expected.add(target.name)
        print(f'{source.name} -> {target.name}')
    return 0


def drop_stale(paths, expected):
    """A source removed or renamed leaves its old target behind otherwise."""
    for stale in sorted(paths):
        if stale.name not in expected:
            stale.unlink()
            print(f'removed stale {stale.name}')


def render_csv() -> int:
    lines = CSV.read_text().split('\n')
    if OWNED_KEY not in lines:
        print(f'{CSV.name} has no owned list under customresourcedefinitions', file=sys.stderr)
        return 1
    start = lines.index(OWNED_KEY) + 1

    # The list runs to the next line that is not part of it, meaning the next
    # non-blank line indented less than the list items.
    end = len(lines)
    for index in range(start, len(lines)):
        line = lines[index]
        if line.strip() and not line.startswith('    '):
            end = index
            break

    block = lines[start:end]
    if BEGIN in block:                      # drop what a previous run wrote
        block = block[:block.index(BEGIN)]
    while block and not block[-1].strip():
        block.pop()

    # A spec descriptor path is a field name, so the same rule applies to it as
    # to a schema property: renaming one would point OLM at a field that is not
    # there.
    for line in block:
        match = re.match(r'\s*path:\s*(\S+)', line)
        if match and 'awx' in match.group(1).lower():
            print(f'{CSV.name} describes a spec path named {match.group(1)}, which this cannot rename', file=sys.stderr)
            return 1

    generated = [BEGIN] + [render(line) for line in block] + [END]
    CSV.write_text('\n'.join(lines[:start] + block + generated + lines[end:]))
    kinds = [line.split(':', 1)[1].strip() for line in generated if line.strip().startswith('kind:')]
    print(f'{CSV.name} owned entries -> {", ".join(kinds)}')
    return 0


def main() -> int:
    sources = sorted(BASES.glob(f'{SOURCE_GROUP}_*.yaml'))
    if not sources:
        print(f'no {SOURCE_GROUP} CRDs under {BASES}', file=sys.stderr)
        return 1

    expected_bases = set()
    if render_files(sources, BASES, expected_bases):
        return 1

    # The sample CRs go the same way, for the same reason: two copies edited by
    # hand end up describing different things.
    expected_samples = set()
    if render_files(sorted(SAMPLES.glob('awx_v1*.yaml')), SAMPLES, expected_samples):
        return 1

    drop_stale(BASES.glob(f'{TARGET_GROUP}_*.yaml'), expected_bases)
    drop_stale(SAMPLES.glob('ascender_v1*.yaml'), expected_samples)

    return render_csv()


if __name__ == '__main__':
    raise SystemExit(main())
